//
// Generated file, do not edit! Created by opp_msgtool 6.2 from DHCPMessage.msg.
//

#ifndef __DHCPMESSAGE_M_H
#define __DHCPMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class DHCPMessage;
/**
 * Class generated from <tt>DHCPMessage.msg:1</tt> by opp_msgtool.
 * <pre>
 * message DHCPMessage
 * {
 *     string msgType;
 *     string deviceType;
 *     string assignedIP;
 *     double leaseTime;
 * }
 * </pre>
 */
class DHCPMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string msgType;
    omnetpp::opp_string deviceType;
    omnetpp::opp_string assignedIP;
    double leaseTime = 0;

  private:
    void copy(const DHCPMessage& other);

  protected:
    bool operator==(const DHCPMessage&) = delete;

  public:
    DHCPMessage(const char *name=nullptr, short kind=0);
    DHCPMessage(const DHCPMessage& other);
    virtual ~DHCPMessage();
    DHCPMessage& operator=(const DHCPMessage& other);
    virtual DHCPMessage *dup() const override {return new DHCPMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getMsgType() const;
    virtual void setMsgType(const char * msgType);

    virtual const char * getDeviceType() const;
    virtual void setDeviceType(const char * deviceType);

    virtual const char * getAssignedIP() const;
    virtual void setAssignedIP(const char * assignedIP);

    virtual double getLeaseTime() const;
    virtual void setLeaseTime(double leaseTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DHCPMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DHCPMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline DHCPMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<DHCPMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DHCPMESSAGE_M_H

